In [1]:
import pandas as pd
df = pd.read_json('test.json')

In [2]:
df

,title,author,date,url,takeaways,text
0,Biden-Harris DOJ Prosecutor Targets Trans Whis...,"[Hans A. von Spakovsky, Sarah Parshall Perry]",2024-11-07,https://www.heritage.org/courts/commentary/bid...,[The weaponization of the U.S. Department of J...,The weaponization of the U.S. Department of Ju...
1,Wisconsin Public Schools’ Gender Policies Shut...,"[Thomas Jipping, Sarah Parshall Perry]",2024-10-23,https://www.heritage.org/gender/commentary/wis...,[Schools are generally in charge of matters su...,The Supreme Court has said that parents’ right...
2,United States v. Skrmetti: Oral Arguments Indi...,[Sarah Parshall Perry],2024-12-13,https://www.heritage.org/gender/commentary/uni...,[Tennessee is one of 26 states that have enact...,"On Wednesday, December 3, the U.S. Supreme Cou..."
3,Trump’s Transgender Orders Are Well Within Exe...,"[Paul J. Larkin, Sarah Parshall Perry]",2025-02-19,https://www.heritage.org/gender/commentary/tru...,[They claim the president’s directive prohibit...,"In two short weeks, President Donald Trump has..."
4,Follow the Law,[Sarah Parshall Perry],2025-02-27,https://www.heritage.org/gender/commentary/fol...,[Hurson’s decision halts the directives of Pre...,It’s difficult to envision a more dizzying exe...
...,...,...,...,...,...,...
299,Elizabeth Fender,[],NaT,https://www.heritage.org/staff/elizabeth-fender,[],Elizabeth Fender is the Senior Brand Advisor f...
300,Parents Beware!,[Rebecca Hagelin],2005-02-11,https://www.heritage.org/marriage-and-family/c...,[],"Parents, does the school your children attend ..."
301,Buyer Beware of CEDAW,[],2002-08-28,https://www.heritage.org/the-constitution/comm...,[],"In late July, when the Senate Foreign Relation..."
302,Why Any Male Student Should Think Twice Before...,[Hans A. von Spakovsky],2015-08-18,https://www.heritage.org/gender/commentary/why...,[],This should terrify any parent whose son is ab...
303,The Problems With CNN Poll Showing Opposition ...,[Elizabeth Fender],2016-06-02,https://www.heritage.org/gender/commentary/the...,[],Between North Carolina’s bathroom law and Pres...

In [3]:
## exploring our data

df.sample(10)

,title,author,date,url,takeaways,text
168,A Court Victory in Texas Against Obamacare’s T...,"[Jay W. Richards, PhD, Sarah Parshall Perry]",2021-08-19,https://www.heritage.org/gender/commentary/cou...,[A federal district court judge blocked an Oba...,The long march of gender ideology through our ...
299,Elizabeth Fender,[],NaT,https://www.heritage.org/staff/elizabeth-fender,[],Elizabeth Fender is the Senior Brand Advisor f...
95,Simon Hankinson,[],NaT,https://www.heritage.org/staff/simon-hankinson,[],Simon Hankinson is a Senior Research Fellow in...
94,Why States Must Define Sex Precisely,"[Jay W. Richards, PhD]",2023-03-31,https://www.heritage.org/gender/commentary/why...,"[Until recently, no precise legal definition o...","Until recently, no precise legal definition of..."
155,Democrats Erase Women Through Budget “Reconcil...,"[Jay W. Richards, PhD, Jared Eckert]",2021-10-15,https://www.heritage.org/gender/commentary/dem...,[The trajectory is unmistakable: Whenever feas...,"According to Senate rules, a reconciliation pa..."
237,Newly Proposed Transgender Policies Could Harm...,"[Emilie Kao, Nicholas Marr]",2019-07-02,https://www.heritage.org/gender/commentary/new...,[],Congress is right when it considers policies t...
196,"Women, Children, and Religious Americans Are N...",[Sarah Parshall Perry],2021-02-25,https://www.heritage.org/religious-liberty/com...,[The Act adds “sex” to some titles like “publi...,"President Joe Biden, only the second Catholic ..."
181,Biden’s New Policy on Transgender Troops Will ...,[Thomas Spoehr],2021-04-14,https://www.heritage.org/defense/commentary/bi...,[The facts show that thrusting individuals wit...,Joe Biden ran a campaign built on a vow to “re...
29,The Biden Administration Redefined “Sex”; What...,"[Jonathan Butcher, Lindsey M. Burke, PhD]",2024-04-26,https://www.heritage.org/gender/commentary/the...,[Our advice to educators: Wait. The administra...,The Biden administration now says that “sex” m...
71,Pride Comes Before the Fall,"[Sarah Parshall Perry, Seth Lucas]",2023-06-07,https://www.heritage.org/civil-society/comment...,"[From the boardroom to the cash register, big ...","From the boardroom to the cash register, big b..."

In [4]:
df.columns

Index(['title', 'author', 'date', 'url', 'takeaways', 'text'], dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      304 non-null    object
 1   author     304 non-null    object
 2   date       279 non-null    datetime64[ns]
 3   url        304 non-null    object
 4   takeaways  304 non-null    object
 5   text       304 non-null    object
dtypes: datetime64[ns](1), object(5)
memory usage: 14.4+ KB

In [6]:
## how to access a column

df['text']

0      The weaponization of the U.S. Department of Ju...
1      The Supreme Court has said that parents’ right...
2      On Wednesday, December 3, the U.S. Supreme Cou...
3      In two short weeks, President Donald Trump has...
4      It’s difficult to envision a more dizzying exe...
                             ...
299    Elizabeth Fender is the Senior Brand Advisor f...
300    Parents, does the school your children attend ...
301    In late July, when the Senate Foreign Relation...
302    This should terrify any parent whose son is ab...
303    Between North Carolina’s bathroom law and Pres...
Name: text, Length: 304, dtype: object

In [7]:
df['author']

0      [Hans A. von Spakovsky, Sarah Parshall Perry]
1            [Thomas  Jipping, Sarah Parshall Perry]
2                             [Sarah Parshall Perry]
3             [Paul J. Larkin, Sarah Parshall Perry]
4                             [Sarah Parshall Perry]
                           ...
299                                               []
300                               [Rebecca  Hagelin]
301                                               []
302                          [Hans A. von Spakovsky]
303                              [Elizabeth  Fender]
Name: author, Length: 304, dtype: object

In [8]:
## cleaning:

## what do we want to do with the data?
## what kind of data do we have? Check each column's data type.
## what kind of data do we need?

In [9]:
## how to access a column?
## how to access a row from that column?

type(df['title'][0])

str

In [10]:
type(df['author'][0])

list

In [11]:
type(df['date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [12]:
## the type of data that we have determines what we can do with it.

# print the data type of each column by checking the first element of each column
for col in df.columns:
    print(f"{col}: {type(df[col][0])}")

title: <class 'str'>
author: <class 'list'>
date: <class 'pandas._libs.tslibs.timestamps.Timestamp'>
url: <class 'str'>
takeaways: <class 'list'>
text: <class 'str'>

In [13]:
## challenge: 

## we want to remove rows that have an empty value in the 'author' column.

In [14]:
## from coplit:

import numpy as np

## uses replace() function -- very useful for cleaning
df['author'].replace('', np.nan, inplace=True)
df = df.dropna(subset=['author'])

In [15]:
# Remove rows where 'date' is NaT
df = df.dropna(subset=['date'])

In [16]:
df.sample(20)

,title,author,date,url,takeaways,text
105,Michigan’s Radical Proposition 3 Ballot Measur...,"[Jay W. Richards, PhD, Emma Waters]",2022-10-06,https://www.heritage.org/life/commentary/michi...,[Proposition 3 would enshrine abortion as an a...,When the U.S. Supreme Court overturned Roe v. ...
232,Will Senate Republicans Swallow Democrats’ Abo...,[Andrea Jones],2019-10-25,https://www.heritage.org/life/commentary/will-...,[The Trump administration has made good on its...,The Trump administration has made good on its ...
7,Tyrants of the Imperious Judiciary: Federal Ju...,[Hans A. von Spakovsky],2025-03-20,https://www.heritage.org/gender/commentary/tyr...,[A federal district court judge just ordered I...,"Every time a radical, out-of-control federal j..."
132,Biden Administration Holds School Lunches Host...,[Sarah Parshall Perry],2022-06-13,https://www.heritage.org/gender/commentary/bid...,"[Such a change will, among other things, open ...",There’s been plenty of sturm und drang over th...
283,Anti-First Amendment Bill Poses Imminent Threa...,[Monica Burke],2018-04-24,https://www.heritage.org/civil-society/comment...,[],A new bill in California claims to protect LGB...
123,Biden’s Push for “Gender-Affirming Care” Betra...,[Tim Doescher],2022-07-07,https://www.heritage.org/gender/commentary/bid...,[We need to help parents protect their childre...,Now that the U.S. Supreme Court has overturned...
181,Biden’s New Policy on Transgender Troops Will ...,[Thomas Spoehr],2021-04-14,https://www.heritage.org/defense/commentary/bi...,[The facts show that thrusting individuals wit...,Joe Biden ran a campaign built on a vow to “re...
180,Fairness for All Act’s Message to Religious Am...,[Sarah Parshall Perry],2021-04-28,https://www.heritage.org/religious-liberty/com...,[Some have proffered the Fairness for All Act ...,America’s greatness rests on its long-standing...
183,Young Children Are Being Targeted With Sexual ...,"[Jared Eckert, Makenna McCoy]",2021-06-11,https://www.heritage.org/marriage-and-family/c...,"[As this year’s LGBT+ Pride Month has shown, y...","Dating back to the 1860s, Americans celebrate ..."
197,Abuse of Women in Sports Under the Guise of Tr...,"[Jared Eckert, Lucy Collins]",2021-02-24,https://www.heritage.org/gender/commentary/abu...,[The left does not seem to want to condemn the...,Perhaps the biggest triumph of the #MeToo move...
5,"Sorry Democrats, but Trump’s “Two Sexes” Execu...",[Sarah Parshall Perry],2025-03-20,https://www.heritage.org/gender/commentary/sor...,"[Under the last presidential administration, p...","Under the last presidential administration, pr..."
19,School Gender Policies Harm Students and Viola...,[Thomas Jipping],2024-04-16,https://www.heritage.org/education/commentary/...,[The centerpiece of these policies is a studen...,"Like others around the country, the Rockford, ..."
154,U.N. Expert Calls for Countries to Embrace Rad...,[Grace Melton],2021-11-04,https://www.heritage.org/gender/commentary/un-...,"[Gender theory is another woke ideology which,...","Victor Madrigal-Borloz, the United Nation’s in..."
275,Transgender Ideology Is Riddled With Contradic...,"[Ryan T. Anderson, Ph.D.]",2018-02-09,https://www.heritage.org/gender/commentary/tra...,[],People say that we live in a postmodern age th...
247,Sexual Identity Laws: A Modern Trojan Horse,[Monica Burke],2019-04-12,https://www.heritage.org/gender/commentary/sex...,[School policy protected the assailant instead...,School should have been the safest place for P...
201,Rand Paul Is Right: Transgender Interventions ...,[Jared Eckert],2021-02-26,https://www.heritage.org/gender/commentary/ran...,[The left will stop at nothing to impose destr...,The left will stop at nothing to impose destru...
55,Don’t Defend Planned Parenthood’s “Gender-Affi...,"[Melanie Israel, Trey Boyd, Macy Petty]",2023-08-10,https://www.heritage.org/gender/commentary/don...,[According to their most recent annual reports...,"In post-Roe America, Planned Parenthood is shi..."
97,"“Gender,” Marxism, and the Search for Power",[Jonathan Butcher],2023-02-09,https://www.heritage.org/progressivism/comment...,[The idea that a young child has a gender iden...,The idea that a young child has a gender ident...
165,Paying Lip Service to Liberty While Imposing R...,"[Jared Eckert, Makenna McCoy]",2021-07-09,https://www.heritage.org/gender/commentary/pay...,[These types of policies impose radical gender...,Schools should be places where students enjoy ...
214,DoD’s Transgender Entrance Policy Exists for a...,[Thomas Spoehr],2020-07-14,https://www.heritage.org/gender/commentary/dod...,"[In deployed situations, a constant flow of me...",Service in the U.S. armed forces is a privileg...

In [ ]:
# remove unicode character

for i in df['text']:
    cleaned_i = i.replace('\xa0', ' ')

In [18]:
df['text']

0      The weaponization of the U.S. Department of Ju...
1      The Supreme Court has said that parents’ right...
2      On Wednesday, December 3, the U.S. Supreme Cou...
3      In two short weeks, President Donald Trump has...
4      It’s difficult to envision a more dizzying exe...
                             ...
298    From education to earnings, American women tod...
300    Parents, does the school your children attend ...
301    In late July, when the Senate Foreign Relation...
302    This should terrify any parent whose son is ab...
303    Between North Carolina’s bathroom law and Pres...
Name: text, Length: 279, dtype: object

In [19]:
# write df to new json file
df.to_json('cleaned.json', orient='records', lines=True)

In [ ]:
# pull out "text" column
text = df['text']

In [22]:
#write text to a file called "text.txt"
with open('text.txt', 'w') as f:
    for line in text:
        f.write(line + '\n\n')

In [ ]:
import pandas as pd

# load without truncation
df = pd.read_json('data_in/cleaned.json', orient='records', lines=True)

In [9]:

df.head()

,title,author,date,url,takeaways,text
0,Biden-Harris DOJ Prosecutor Targets Trans Whis...,"[Hans A. von Spakovsky, Sarah Parshall Perry]",2024-11-07,https://www.heritage.org/courts/commentary/bid...,[The weaponization of the U.S. Department of J...,The weaponization of the U.S. Department of Ju...
1,Wisconsin Public Schools’ Gender Policies Shut...,"[Thomas Jipping, Sarah Parshall Perry]",2024-10-23,https://www.heritage.org/gender/commentary/wis...,[Schools are generally in charge of matters su...,The Supreme Court has said that parents’ right...
2,United States v. Skrmetti: Oral Arguments Indi...,[Sarah Parshall Perry],2024-12-13,https://www.heritage.org/gender/commentary/uni...,[Tennessee is one of 26 states that have enact...,"On Wednesday, December 3, the U.S. Supreme Cou..."
3,Trump’s Transgender Orders Are Well Within Exe...,"[Paul J. Larkin, Sarah Parshall Perry]",2025-02-19,https://www.heritage.org/gender/commentary/tru...,[They claim the president’s directive prohibit...,"In two short weeks, President Donald Trump has..."
4,Follow the Law,[Sarah Parshall Perry],2025-02-27,https://www.heritage.org/gender/commentary/fol...,[Hurson’s decision halts the directives of Pre...,It’s difficult to envision a more dizzying exe...